### ISSUE TITLE
Re-initializing main() because the training of light MLP diverged and all the values ​​are zero. 

### ISSUE THREAD

**Issue by ABCAI93** [sbharadwajj/flare#4]
Thanks for open source such a great project！
When I trained the yufeng and marcel data sets, errors quickly occurred: Re-initializing main() because the training of light MLP diverged and all the values ​​are zero. 
Code tested on RTX 3090Ti
How can I solve this problem?

**Comment by sbharadwajj** [comment]
Hi

Did the code restart or crash? 
typically it should restart.

**Comment by ABCAI93** [comment]
> Hi
> 
> Did the code restart or crash? typically it should restart.

It keeps restarting and then keeps repeating this error. 
I want to know what causes this error and how I can solve it.
Thanks.

**Comment by sbharadwajj** [comment]
Hi,

The only solution unfortunately is to restart the code. I did not find time to check if it is a GPU problem because in one of the GPU I used, it did not occur and ran into the problem only on other GPUs. 

So please try restarting the code. If it still does not work, let me know!

The error is caused because we do not use an activation function for the output layer of the light MLP to keep the values unconstrained as we have tonemap the values.

**Comment by yydxlv** [comment]
The same problem is occured on A800

**Comment by sbharadwajj** [comment]
Hi, 

does the code never work or does it happen only a few times?

**Comment by ABCAI93** [comment]
> Hi,
> 
> does the code never work or does it happen only a few times?


Unfortunately,  the code never work

**Comment by sbharadwajj** [comment]
Hi,
Can you please run the code once again and copy-paste the exact log that is printed on the terminal?

**Comment by Orange-Ctrl** [comment]
Hi,
I got the same problem and I also run the code on RTX 3090Ti. The following is what printed on the terminal. 
`Using device cuda:4
loading train views...
loaded 2904 views
loaded 77 views
creating the FLAME Decoder
Rasterizing: ['mask', 'position', 'normal', 'canonical_position']
==========================================
Training Deformer
STAGE 1: Using positional encoding (NeRF) for intrinsic materials
{'material_mlp_ch': 5, 'light_mlp_ch': 3, 'material_mlp_dims': [128, 128, 128, 128], 'light_mlp_dims': [64, 64]}
----------------------------------------------------------------------------------------------------
Re-initializing main() because the training of light MLP diverged and all the values are zero.
----------------------------------------------------------------------------------------------------
Rasterizing: ['mask', 'position', 'normal', 'canonical_position']
==================================================================================
`

**Comment by Orange-Ctrl** [comment]
Hi,
I run the code on rtx3090 and got the same problem.
![Snipaste_2023-12-06_16-56-40](https://github.com/sbharadwajj/flare/assets/65001141/93a1e777-680c-4649-979e-5237b59b2c21)

**Comment by Orange-Ctrl** [comment]
I find the problem, it's because lack of the module [robust_loss_pytorch](https://github.com/jonbarron/robust_loss_pytorch). It runs successfully now!
![image](https://github.com/sbharadwajj/flare/assets/65001141/2218b333-976d-42f0-ad30-dad8e8f2ec8f)

**Comment by ABCAI93** [comment]
> Hi, I run the code on rtx3090 and got the same problem. ![Snipaste_2023-12-06_16-56-40](https://private-user-images.githubusercontent.com/65001141/288348993-93a1e777-680c-4649-979e-5237b59b2c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTcxNzEsIm5iZiI6MTcwMTg1Njg3MSwicGF0aCI6Ii82NTAwMTE0MS8yODgzNDg5OTMtOTNhMWU3NzctNjgwYy00NjQ5LTk3OWUtNTIzN2I1OWIyYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEwMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZWZlYjA4ODEyYTg1OGQ5MTYzZjc2ZjFmODVmN2VmZTdlOTA4MDNmZTI0NWI2NTZjNTgyMzg4ZTc5NTc1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sOx3EVBH9Z1m_H3SkoCbPfDXR-Cmhqa1vH6KE6BInC4)

yeah, pip install git+https://github.com/jonbarron/robust_loss_pytorch   
it works!

**Comment by sbharadwajj** [comment]
Glad to hear it works now :) 

I think I forgot to include it in the requirements.txt. 

@Orange-Ctrl i can also see a warning of tinycudann installation in your log image. You have compiled tinycudann on a different GPU device and running it on another one. To get the best performance, please make sure it is properly installed.

**Comment by zydmu123** [comment]
Sorry to bother you @sbharadwajj But it really doesn't work even with the installation of above "robust_loss_pytorch", my GPU is RTX3090, never run successfully for once! Could you give me some help, really thanks!

**Comment by Yingyan-Xu** [comment]
Hi @zydmu123 did you manage to run the code in the end? I'm having the same issue on RTX3090 and I also tried `robust_loss_pytorch` and it didn't work.

**Comment by sbharadwajj** [comment]
@Yingyan-Xu did you verify if the mask if correct? Can you quickly save the mask and check?
